# Generated by Django 5.2.3 on 2025-07-11 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('violent', 'Violent Crime'), ('property', 'Property Crime'), ('cyber', 'Cybercrime'), ('fraud', 'Fraud'), ('other', 'Other')], default='other', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('penalty', models.TextField(blank=True, null=True)),
                ('law_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('reportable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=50)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skin_color', models.CharField(max_length=50)),
                ('hair_color', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='suspect_pictures/')),
                ('known_associates', models.TextField(blank=True, null=True)),
                ('previous_criminal_records', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('Arrested', 'Arrested'), ('Under Investigation', 'Under Investigation'), ('Released', 'Released')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainant_full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('incident_datetime', models.DateTimeField()),
                ('crime_description', models.TextField()),
                ('relationship_to_incident', models.CharField(choices=[('victim', 'Victim'), ('witness', 'Witness'), ('relative', 'Relative'), ('neighbor', 'Neighbor'), ('anonymous', 'Anonymous'), ('other', 'Other')], max_length=50)),
                ('location_of_crime', models.CharField(max_length=200)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('evidence_provided', models.FileField(blank=True, null=True, upload_to='complaint_evidence/')),
                ('complaint_status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('crime_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.crimecatalog')),
            ],
        ),
        migrations.CreateModel(
            name='Criminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('criminal_id_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='criminal_photos/')),
                ('date_of_conviction', models.DateField()),
                ('sentence_details', models.CharField(choices=[('Jail Term', 'Jail Term'), ('Fine', 'Fine'), ('Probation Details', 'Probation Details')], max_length=50)),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('known_associates', models.TextField(blank=True, null=True)),
                ('crime_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.crimecatalog')),
            ],
        ),
    ]
