# Generated by Django 5.2.3 on 2025-07-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='crime_severity_estimate',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='crime_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='incident_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='other_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reporter_relationship',
            field=models.CharField(blank=True, choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Concerned Citizen', 'Concerned Citizen'), ('Other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='witnessed_directly',
            field=models.BooleanField(default=False),
        ),
    ]
