# Generated by Django 5.2.3 on 2025-07-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint_crime_severity_estimate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='preferred_response_channel',
            field=models.CharField(choices=[('Phone Call', 'Phone Call'), ('Email', 'Email'), ('SMS', 'SMS'), ('None', 'None')], default='None', max_length=100),
        ),
    ]
