# Generated by Django 5.2.3 on 2025-07-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_complaint_is_emergency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='incident_datetime',
            new_name='date_time_of_incident',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='evidence_provided',
            new_name='evidence',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complainant_full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='location_of_crime',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='relationship_to_incident',
            new_name='relationship',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='crime_severity_estimate',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='crime_title',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='is_emergency',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='other_notes',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='preferred_response_channel',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='reporter_relationship',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='witnessed_directly',
        ),
    ]
