# Generated by Django 5.2.3 on 2025-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_incident_datetime_complaint_date_time_of_incident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('incident_datetime', models.DateTimeField(blank=True, null=True)),
                ('crime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_description', models.TextField(blank=True, null=True)),
                ('suspect_description', models.TextField(blank=True, null=True)),
                ('location_of_crime', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence_provided', models.FileField(blank=True, null=True, upload_to='evidence/')),
                ('crime_severity_estimate', models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], max_length=10, null=True)),
                ('witnessed_directly', models.BooleanField(default=False)),
                ('reporter_relationship', models.CharField(blank=True, choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Concerned Citizen', 'Concerned Citizen'), ('Other', 'Other')], max_length=50, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('preferred_response_channel', models.CharField(choices=[('Phone Call', 'Phone Call'), ('Email', 'Email'), ('SMS', 'SMS'), ('None', 'None')], default='None', max_length=100)),
                ('other_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
