# Generated by Django 5.2.3 on 2025-07-21 09:55

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_complaint_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='crime_description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='crime_severity_estimate',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Critical', 'Critical')], default='No description provided.', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='crime_type',
            field=models.CharField(default='No description provided.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='incident_datetime',
            field= models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='location_of_crime',
            field=models.CharField(default='No description provided.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='reporter_relationship',
            field=models.CharField(choices=[('Victim', 'Victim'), ('Witness', 'Witness'), ('Concerned Citizen', 'Concerned Citizen'), ('Other', 'Other')], default='No description provided.', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='suspect_description',
            field=models.TextField(default='No description provided.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crimecatalog',
            name='crime_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
