# Generated by Django 5.2.3 on 2025-07-21 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_anonymouscomplaint_crime_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymouscomplaint',
            name='incident_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_time_of_incident',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='criminal',
            name='date_of_conviction',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
